# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a lightweight Linux image
FROM node:14-alpine

# Install Chrome dependencies
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ttf-freefont \
    && rm -rf /var/cache/*

# Set the working directory
WORKDIR /app

# Copy all extension files into the image
COPY . .

# Instruct the container to run Chrome
CMD ["chromium-browser", "--headless", "--no-sandbox", "--disable-gpu", "--remote-debugging-port=9222"]
